### ISSUE TITLE
Carrots not getting recognized in shop

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoEnchants#125]
**Describe the bug**
Hey I was testing the autosell addon and I find an issue, no idea why but carrots aren't selling when they are on sale in my shop

**To Reproduce**
1. Put the autosell enchant on your hoe
2. Add carrots to sell in your shop
3. Break some crops with the hoe that contains the autosell enchantements
4. And it's not selling (check gif)

**Expected behavior**
It should sell

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://gyazo.com/726040a4ae2bcd720fbd4b8672f294d9)

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
Eco: 6.20.4
EcoEnchants 8.29.4

**Additional context**
None

**Comment by 0ft3n** [comment]
> **Describe the bug** Hey I was testing the autosell addon and I find an issue, no idea why but carrots aren't selling when they are on sale in my shop
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Put the autosell enchant on your hoe
> 2. Add carrots to sell in your shop
> 3. Break some crops with the hoe that contains the autosell enchantements
> 4. And it's not selling (check gif)
> 
> **Expected behavior** It should sell
> 
> **Screenshots** [If applicable, add screenshots to help explain your problem.](https://gyazo.com/726040a4ae2bcd720fbd4b8672f294d9)
> 
> **Server Information (please complete the following information):**
> 
> * Version: (output of `/ver` command)
>   This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
>   You are running the latest version
> * Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
>   Eco: 6.20.4
>   EcoEnchants 8.29.4
> 
> **Additional context** None

Did not really use ShopGUI+, but if it has shop config, can you please paste it there?

**Comment by LuluxClient** [comment]
Here is a config for the carrots
```
agriculture_carotte:
  name: "&8Agriculture : Carotte"
  size: 36
  fillItem:
    material: gray_stained_glass_pane
    name: " "

  items:

    retour:
      type: dummy
      item:
        itemsAdder: "icon_retour"
        name: "&cRetour"
        lore:
          - "#B1BBBCRevenir à la catégorie :"
          - "#EFEFEFAgriculture"
          - " "
          - "#50D8E3→ Cliquez pour revenir en arrière"
        quantity: 1
      commandsOnClickConsole:
        - shop %PLAYER% agriculture
      slot: 31

    pieces:
      type: special
      special: balance
      slot: 33  




    carotte:
      type: item
      item:
        material: carrot
        name: "#FFB025Carotte"
        quantity: 1
      buyPrice: 4.4
      sellPrice: 0.4
      slot: 12

    carotte_doree:
      type: item
      item:
        material: golden_carrot
        name: "#FFB025Carotte dorée"
        quantity: 1
      buyPrice: 99999
      sellPrice: 1
      slot: 14
      ```
