### ISSUE TITLE
Enchant lore sort-by-length does not work when sort-by-type is enabled.

### ISSUE THREAD

**Issue by NightFuryStrike** [Auxilor/EcoEnchants#158]
**Describe the bug**
Greetings, I would like to report that the **sort-by-length: true** configuration option does not function when **sort-by-type: true** is enabled.

Observed behavior:
![image](https://user-images.githubusercontent.com/56176412/154087220-11418e81-6891-47c2-b059-b2f5a80550bb.png)

**Expected behavior**
When both options are enabled, I expect enchants to first be grouped together by their type as listed in the config, and then sorted by length within their type.

Example of expected behavior:
![image](https://user-images.githubusercontent.com/56176412/154084448-f66a6b22-881b-43d1-a898-98dfd69dd277.png)

**To Reproduce**
Edit config.yml and set the following options:
```
lore:
  sort-by-type: true
  sort-by-length: true
  sort-by-rarity: false
  type-ordering:
  - normal
  - special
  - artifact
  - spell
  - curse
```

**Server Information (please complete the following information):**
- Version: Paper-185 (1.18.1)
- Version of plugin and eco: Eco (6.24.0) - EcoEnchants (8.33.1)

**Additional context**
Ticket ecoenchants-0099 on Discord.
