### ISSUE TITLE
Problem with nametags and item naming

### ISSUE THREAD

**Issue by Xen0Xys** [Auxilor/EcoEnchants#188]
**Describe the bug**
When naming a nametag "jeb_", the sheep do not become rainbow when applying it

**To Reproduce**
1. Launch a server with EcoEnchant on it
2. Rename a nametag "jeb_"
3. Apply it on a sheep
4. See that the sheep do not become rainbow

**Expected behavior**
The renamming work good

**Screenshots**
Here you can see first a normal nametag, and second a nametag do with EcoEnchant on the server (get from playerdata file)
![image](https://user-images.githubusercontent.com/47594493/158082451-a5877081-82ed-4789-b0ba-f9602d097cd8.png)

**Server Information (please complete the following information):**
- git-Purpur-1565 (MC: 1.18.1)
- Eco 6.28.3 and EcoEnchant 8.48.1

**Additional context**
Eco config:
```yaml
#
# eco
# by Auxilor
villager-display-fix: false
use-fast-collated-drops: true
use-lower-protocollib-priority: false
use-display-frame: true
display-frame-ttl: 17
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: database
  user: username
  password: passy
  threads: 2
  async-reads: false
  connections: 10
async-display:
  log-errors: true
  emergency:
    enabled: false
    cutoff: 18
  ratelimit:
    enabled: false
    cutoff: 4
    timeframe: 1
  disable-on-types:
  - anvil
  always-enabled: false
use-safer-namespacedkey-creation: false
log-full-extension-errors: false
```

EcoEchant config:
```yaml
#
# EcoEnchants
# by Auxilor
#

allow-on-npc: false # If enchantments should activate against NPCs.

commands:
  enchantinfo:
    show-target-group: true # Show name of target group rather than individual items

anvil:
  rework-cost: false # Use vanilla rework penalty
  allow-unsafe-levels: false # Allow unsafe enchantments like Sharpness 6 by combining 2 Sharp 5.
  allow-combining-unsafe: false # Allow further combining unsafe levels, eg Sharp 6 + Sharp 6 = Sharp 7.
  allow-existing-unsafe-levels: true # Allow combining existing unsafe enchantments like Sharpness 6
  
  cost-exponent: # Increase value of each extra level by the exponent^levels
    enabled: true # Use exponent
    exponent: 0.95 # Exponent. Beware that slight changes to this value may cause huge changes in cost.
  
  hard-cap: # Completely limit the amount of enchantments that can be placed on an item
    enabled: false # Enable a hard cap
    cap: 10 # Most enchantments allowed on an item

lore:
  use-numerals: true
  use-numbers-above-threshold: 10 # After level 10, enchantments will display as Name Number, eg: Sharpness 25 instead of Sharpness XXV
  
  above-other-lore: true # If enchantments should be displayed above other lore
  
  # If above max level enchantments should be formatted differently
  # Format is available in lang.yml
  above-max-level:
    reformat: true
    numbers-only: true # If only the numbers should be reformatted
  
  
  sort-by-type: false # Sort enchantments by type
  sort-by-length: false # Sort enchantments by length
  sort-by-rarity: false # Sort enchantments by rarity.
  # Any combination of the above options is valid

  require-target: true # Only display items included in target.yml
  
  type-ordering: # Only used if sort-by-type is enabled - top to bottom
    - normal
    - special
    - artifact
    - spell
    - curse
  
  rarity-ordering: # Only used if sort-by-rarity is enabled - top to bottom
    - common
    - uncommon
    - rare
    - epic
    - legendary
    - special
    - veryspecial
  
  describe: # Describe enchantments in lore
    enabled: true
    before-lines: 5 # Describe before or equal to number of enchantments
    wrap: 30 # Word wrap after number of characters
    at-bottom: false # If descriptions should be shown after all enchantments rather than under each one
  
  # Ensure that describe and shrink have no overlap as this may cause errors

  shrink: # Collapse large amount of enchantments
    enabled: true
    after-lines: 9 # Collapse after number of enchantments
    maximum-per-line: 2 # Maximum number of enchantments to have in 1 line
  prefix: []
  suffix: []
  prefix-on-books: false

enchanting-table:
  enabled: true # Enable EcoEnchants through an enchanting table
  book-times-less-likely: 2 # Times less likely to get an EcoEnchant on a book to balance them out. Don't recommend editing.
  maximum-obtainable-level: 30 # Max level for enchanting table. Vanilla default is 30, change if you have a plugin that edits this.
  special-bias: 0.7 # Value between 0-1 dictating rarity of high-level special enchantments. 0 is no extra bias, 1 is only level 1.
  notify-on-special: # Tell player in chat and make a sound when they get a special enchantment
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    pitch: 1.5
    show-particles: true
    particle-amount: 26
  
  cap-amount: # Prevent getting above a certain amount of enchantments
    enabled: true # Enable capping
    limit: 5 # Cap at amount
  
  reduce-probability: # Reduce probability of adding new enchantment by factor after each enchantment added
    enabled: true # Enable reduction
    factor: 2.2 # Factor to reduce probability by. Done as compound, so second pass is (factor) times less likely than first, third less likely than second, etc

villager:
  enabled: true # Enable EcoEnchants through villagers
  book-times-less-likely: 7 # Times less likely to get an enchantment from a book with a villager. Recommended to be higher as books can only have one enchantment on them.
  notify-on-special: # Show particles when the villager unlocks a special enchantment trade
    enabled: true
    particle-amount: 14
  
  reduce-probability: # Reduce probability of adding new enchantment by factor after each enchantment added. Does not apply to books as they only ever contain one enchantment.
    enabled: true # Enable reduction
    factor: 5 # Factor to reduce probability by. Done as compound, so second pass is (factor) times less likely than first, third less likely than second, etc

loot:
  enabled: true # Enable EcoEnchants through loot chests
  book-times-less-likely: 2
  
  reduce-probability: # Reduce probability of adding new enchantment by factor after each enchantment added. Does not apply to books as they only ever contain one enchantment.
    enabled: true # Enable reduction
    factor: 7.5 # Factor to reduce probability by. Done as compound, so second pass is (factor) times less likely than first, third less likely than second, etc

types:
  special:
    allow-multiple: true # Allow multiple special enchantments on a single item
    cooldown-in-actionbar: true # Show cooldown messages in the action bar rather than in chat
  artifact:
    allow-multiple: false # Allow multiple artifacts on a single item (can cause lag!)

rarity:
  vanilla-rarity: common # Vanilla enchantments do not have an EcoEnchants rarity - what rarity should they have?
  vanilla-treasure-rarity: epic # Treasure enchantments do not appear in vanilla enchanting tables (Mending, Soul Speed, Frost Walker)
# The above options *do not* affect actual enchantment rarities. They are purely for cosmetic purposes, like in item lores.

advanced:
  force-dropqueue: true
  # When combined with collate, this massively reduces calls to getItemMeta, which can hurt performance when many enchants are on an item.
  # Enabling this option makes all drops go through telekinesis listeners
  lore-getter:
    # This converts enchantments with matching names from other enchantment plugins from lore into real enchantments.
    # This is experimental not recommended to be used for extended periods of time: enchantments are automatically converted.
    # Only use this if absolutely necessary as it may cause some bugs.
    enabled: false
    aggressive: false
  # Aggressive mode converts all items in all inventories when opened.
  # This will most likely have a significant performance penalty.
  hide-fixer:
    # Fixes some items obtained in older versions with a bug that caused enchantments to be hidden.
    # Works both in packets to display the enchants to the client as well as changing the server-side item too.
    # Only use this option if you've encountered this bug as it may strip HideEnchants from items that you might not expect it to.
    enabled: false
    aggressive: false
    # Aggressive mode converts all items in all inventories whenever revealed.
    # This may impact performance.
    force: false # If **all** items should have hide enchants removed - absolute last ditch effort, most likely to break other things.
  hard-disable:
    # Fixes potential problems with other plugins where the enchantments are still present when disabled.
    # Enabling this prevents the enchantments from being registered with the server at all when disabled.
    # There may be some unknown problems with this, but will fix bugs with plugins such as Slimefun.
    # Hard disabled enchantments will not update on /ecoreload. You will have to restart your server.
    enabled: false
  dual-registration:
    # Fixes potential plugin conflicts/serialization issues when updating from a version before 7.3.0.
    # Registers byName both the internal enchantment name (new method) and the display name (old method).
    # There may be potential bugs with having duplicate enchantments, so enable this only if you need it.
    enabled: true
  level-clamp:
    # Helps reverse players who have illegal above-max-level enchantments.
    # When holding an item, any enchantments above their max level will be set to the max level in order to prevent illegal items.
    # Players with ecoenchants.bypasslevelclamp permission will be ignored.
    # This may impact performance.
    enabled: false
    # If the item should be deleted rather than have the enchantment level capped.
    delete-item: false
  remove-illegal:
    # Helps reverse players who have enchantments on illegal items.
    # When holding an item, any enchantments present on the item that shouldn't be will be removed.
    # Players with ecoenchants.allowillegal permission will be ignored.
    # This may impact performance.
    enabled: false
    # If the item should be deleted rather than have the enchantment removed.
    delete-item: false
  remove-disabled:
    # Remove invalid / disabled enchantments from items server-side
    # Useful if you're disabling enchantments permanently and don't mind removing them from existing players
    # Also helps remove deleted enchantments or enchantments from old plugins
    enabled: false
  hard-cap-clamp:
    # Helps reverse players who have items with more enchants than the hard cap.
    # Players with ecoenchants.anvil.bypasshardcap permission will be ignored.
    # This may impact performance.
    enabled: false
use-faster-move-trigger: true
cooldown:
  in-actionbar: true
  sound:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
cannot-afford:
  in-actionbar: true
  sound:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
raytrace-distance: 80
block-item-drop-place-check: true
cannot-afford-type:
  in-actionbar: true
  sound:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_PLING
    pitch: 0.5
point-names:
  example_point: Nicely Formatted Point
potions:
  icon:
    permanent: true
    triggered: true
  ambient:
    permanent: false
    triggered: true
  particles:
    permanent: false
    triggered: true
```
