### ISSUE TITLE
Error when enabled vanillaenchantments.yml

### ISSUE THREAD

**Issue by ArtifactyNight** [Auxilor/EcoEnchants#222]
It's error on startup when im enabled feature in `vanillaenchants.yml` file

error: https://www.toptal.com/developers/hastebin/wuhajinusa.md
full logs: https://www.toptal.com/developers/hastebin/situquzeka.yaml: 

config.yml
```yml
#
# Allows for modifying certain aspects of vanilla enchantments
#
enabled: true

# Set custom max levels for vanilla enchantments.
# To do this, add each enchantment like this:
# - "<key>:4"
# For example, to allow efficiency 6 and protection 5, you would do this:
# max-levels:
#   - "efficiency:6"
#   - "protection:5"
#
# Currently, it is *not* possible to modify the enchantment levels from enchanting tables.
# It will work with anvils however, but since it is still possible to get enchantments at their vanilla
# max levels, then it isn't recommended to lower the max level of a vanilla enchantment, only to raise it.
max-levels:
  - "efficiency:7"
  - "durability:8"
  - "fire_aspect:9"
  - "sharpness:10"
  - "power:7"
  - "looting:5"
  - "fortune:5"

# Set custom conflicts for vanilla enchantments.
# To do this, add each enchantment like this:
# - "<key>:<conflict 1 key>:<conflict 2 key>:<conflict 3 key>..... etc"
# For example, to make mending conflict with efficiency and sharpness, you would do this:
# conflicts:
#   - "mending:efficiency:sharpness"
#
# If you want to remove all conflicts, set the list to 'none':
# conflicts:
#   - "mending:none"
#
# Beware that this will *override* conflicts, not add to them.
conflicts: []
```

EcoEnchants version: 8.70.0 (It's still error when update to 8.70.1)
eco version: 6.35.12
