### ISSUE TITLE
Nerfing enchants (like lowering max level) does not apply to items retroactively

### ISSUE THREAD

**Issue by cloakfox** [Auxilor/EcoEnchants#71]
As the title says, we are making balancing changes on the fly based on player feedback, but we are now dealing with players having/owning extremely OP items from before our changes.

Is there a way to force an enchantments max level on already enchanted item?

**Comment by Akiranya** [comment]
What you want is possible. I did it by BanItems.

My OPs accidently gave out some enchantments that was way too beyond what it should be (like Water affinity of level 50).

Here is my Banitems config. Basically it detects the enchantments with too high levels when the player attacks something with the weapon, and we force only the enchantment on the weapon to be normal level.

BanItem/config.yml

```
(omitted)
...
blacklist:
  '*':
    wateraffinity_sword:
      attack:
        log: true
        run:
        - lp user {player} permission settemp essentials.enchant true 1s
        - lp user {player} permission settemp essentials.enchantments.water_affinity
          true 1s
        - sudo {player} enchant water_affinity 5
        - eco give {player} 60 P
        - sudo {player} me My water affinity of level 50 has become normal and I got 60P as relief
```

BanItem/customitems.yml
```
wateraffinity_sword:
  material: "#_SWORD"
  enchantment-contains:
    - water_affinity:50
```
